#!/usr/bin/env python

import rospy
from turtlebot3_wall_follower import controller

def node_init():
    try:
        rospy.init_node("burger_controler")
        burger = controller.Burger()        
 
        burger.follow_wall()

        

    except rospy.ROSInterruptException:

        rospy.logerr("Something went wrong")


if __name__  == "__main__":
    node_init()
    