#!/usr/bin/env python
import rospy
from turtlebot3_wall_follower.server import BurgerServer



def start_server():
    try:
        rospy.init_node("burger_server")
        server = BurgerServer()
        server.start()
    except rospy.ROSInterruptException:
        rospy.logerr("You pressed CTRL+C or something went wrong...")


if __name__ == "__main__":
    start_server()
